# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180501_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
