# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


def update_slugs(apps, schema_editor):
    """Replace old 'active' status with published"""
    from orb.courses.models import Course
    for course in Course.objects.all():
        course.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_oppia_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(update_slugs, empty_reverse),
    ]
