# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0049_survey_questions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resource',
            managers=[
                ('resources', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcecriteria',
            managers=[
                ('criteria', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourceworkflowtracker',
            managers=[
                ('workflows', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reviewerrole',
            managers=[
                ('roles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('tags', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='create_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='update_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='create_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_url_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='update_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_url_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
