# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0052_auto_20180501_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_file_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_file_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_relationship_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_relationship_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_url_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_url_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
