# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0053_auto_20180501_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetag',
            name='create_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcetag_create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
