# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orb', '0054_auto_20180501_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='sha1',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
